[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:NEMtropy.*
    ignore::numba.core.errors.NumbaExperimentalFeatureWarning
    ignore:FigureCanvasAgg is non-interactive.*:UserWarning
    ignore:No artists with labels found.*:UserWarning
